### ISSUE TITLE
Define pets table schema

### ISSUE THREAD

**Issue by jecortez** [jecortez/DenverDoge#4]
Our Fields:
id - Auto incrementing long? UUID? dealer's choice
created_at - Timestamp
updated_at - Timestamp
source_id (foreign key to sources table) 
batch_id (UUID for knowing which run of the ingestion process this is)
external_id (UUID of the pet in the external system, ID from PetFinder object)

Fields we want from PetFinder
url - URL on petfinder / URL on shelter
type [DOG / CAT]
species [DOG / CAT] (it's seperate because PF also works for hampsters and other pets)
age - they have it as an enum (YOUNG / ADULT / BABY / SENIOR)
gender (Male / Female)
size (Small / Medium / Large)
coat (Short / Medium / Long)
tags [List of Strings]
name String
description String
photos String (URL of a photo)
status (Adoptable / Adopted / Found, and we can have our own statuses as well
breeds_primary - String
breeds_secondary - String
breeds_mixed - Bool
colors_primary - String
colors_secondary - String
colors_tertiary - String
attributes_spayed_neutered - Bool
attributes_house_trained - Bool
attributes_declawed - Bool
attributes_special_needs - Bool
attributes_shots_current - Bool
environment_children - Bool
environment_dogs - Bool (good with other dogs?)
environment_cats - Bool (good with other cats)
animal_id -- will eventually become `external_id` defined above

Not included fields from PetFinder (and why)
organization_id - seems to only be used for their purposes
status_changed_at - we can use our updated_at field for this 
published_at - ^^
contact.email - All contact information will either be accessible via the link (which will send users directly to the source page) or via the sources (if we start to ingest data from shelters)
contact.phone
contact.address.address1
contact.address.address2
contact.address.city
contact.address.state
contact.address.postcode
contact.address.country
animal_type - redundant field imo wrt batches

**Comment by anlewis** [comment]
Schema:

```
ActiveRecord::Schema.define(version: 2019_10_26_165819) do

  create_table "pets", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
    t.bigint "source_id", null: false
    t.string "batch_id"
    t.string "external_id"
    t.string "url"
    t.string "type"
    t.string "species"
    t.string "age"
    t.string "gender"
    t.string "size"
    t.string "coat"
    t.string "tags"
    t.string "name"
    t.string "description"
    t.string "image_url"
    t.string "status"
    t.string "breeds_primary"
    t.string "breeds_secondary"
    t.boolean "breeds_mixed"
    t.string "colors_primary"
    t.string "colors_secondary"
    t.string "colors_tertiary"
    t.string "attributes_activity_level"
    t.boolean "attributes_spayed_neutered"
    t.boolean "attributes_house_trained"
    t.boolean "attributes_declawed"
    t.boolean "attributes_special_needs"
    t.boolean "attributes_shots_current"
    t.boolean "environment_children"
    t.boolean "environment_dogs"
    t.boolean "environment_cats"
    t.index ["source_id"], name: "index_pets_on_source_id"
  end

  create_table "sources", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
    t.string "name"
  end

  create_table "surveys", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.boolean "children"
    t.boolean "dogs"
    t.boolean "cats"
    t.string "activity_level"
    t.index ["user_id"], name: "index_surveys_on_user_id"
  end

  create_table "swipes", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.bigint "pet_id", null: false
    t.boolean "liked"
    t.index ["pet_id"], name: "index_swipes_on_pet_id"
    t.index ["user_id"], name: "index_swipes_on_user_id"
  end

  create_table "users", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
    t.string "name"
  end

  add_foreign_key "pets", "sources"
  add_foreign_key "surveys", "users"
  add_foreign_key "swipes", "pets"
  add_foreign_key "swipes", "users"
end
```
